#!/usr/bin/env ruby

# from http://errtheblog.com/posts/89-huba-huba

home = File.expand_path('~')

Dir['*'].each do |file|
	next if file =~ /install/
	next if file =~ /readme/
	target = File.join(home, ".#{file}")
	print "Linking #{file} to #{target}"
	print "\n"
	`ln -si #{File.expand_path file} #{target}`
end

	
	

